name: GitHub Actions Build
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32c6
        path: ''
    - name: archive artifact
      run: |
        zip /tmp/esp-coordinator-escp32-c6-usb-${{ github.tag }}.zip build/bootloader/bootloader.bin \
          build/esp-coordinator.bin build/ota_data_initial.bin build/partition_table/partition-table.bin
    - name: upload release artifact
      if: github.event.action == 'published' && github.event == 'release'
      uses: actions/upload-release-asset@v1
      with:
        path: build/esp-coordinator-escp32-c6-usb-${{ github.tag }}.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: /tmp/*.zip
        compression-level: 9
        if-no-files-found: error